name 'mosen-plist'
author 'mosen'
description 'Property list modification'
source 'https://github.com/mosen/puppet-plist.git'
summary 'This module manages values in property list (.plist) files for OS X'
license 'MIT'
version '0.0.1'
